<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-24T20:43:11 IST" name="Default suite" finished-at="2021-09-24T20:43:33 IST" duration-ms="21483">
    <groups>
    </groups>
    <test started-at="2021-09-24T20:43:11 IST" name="Default test" finished-at="2021-09-24T20:43:33 IST" duration-ms="21483">
      <class name="LoginTestPage.LoginTestPageGitHub">
        <test-method is-config="true" signature="initialization()[pri:0, instance:LoginTestPage.LoginTestPageGitHub@5e82df6a]" started-at="2021-09-24T20:42:58 IST" name="initialization" finished-at="2021-09-24T20:43:11 IST" duration-ms="13559" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="create_account()[pri:1, instance:LoginTestPage.LoginTestPageGitHub@5e82df6a]" started-at="2021-09-24T20:43:11 IST" name="create_account" finished-at="2021-09-24T20:43:25 IST" duration-ms="13703" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_account -->
        <test-method signature="reset_password()[pri:2, instance:LoginTestPage.LoginTestPageGitHub@5e82df6a]" started-at="2021-09-24T20:43:25 IST" name="reset_password" finished-at="2021-09-24T20:43:30 IST" duration-ms="5248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reset_password -->
        <test-method signature="login()[pri:3, instance:LoginTestPage.LoginTestPageGitHub@5e82df6a]" started-at="2021-09-24T20:43:30 IST" name="login" finished-at="2021-09-24T20:43:33 IST" duration-ms="2362" status="FAIL">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Destination 'D:\Bhushan\pageobjectmodel1\GitHubLoginPage\target\screenshot' exists but is a directory]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Destination 'D:\Bhushan\pageobjectmodel1\GitHubLoginPage\target\screenshot' exists but is a directory
at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1300)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:797)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:747)
at Base.BaseClass.screenShot(BaseClass.java:51)
at LoginTestPage.LoginTestPageGitHub.login(LoginTestPageGitHub.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="Close()[pri:0, instance:LoginTestPage.LoginTestPageGitHub@5e82df6a]" started-at="2021-09-24T20:43:33 IST" name="Close" finished-at="2021-09-24T20:43:33 IST" duration-ms="384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- LoginTestPage.LoginTestPageGitHub -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
